import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://s7d4.scene7.com/is/image/WolverineWorldWide/MRLM-J037501-041024-S24-000?$dw-pdp-primary$",
    title: "Men's Moab Speed 2®",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2500",
    company: "Merrell",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/38debae04ae44d63aa88af2301524e7d_9366/Pharrell_Williams_NMD_S1_RYAT_Shoes_Green_IE4686_01_standard.jpg",
    title: "Pharrell Williams NMD S1",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹24,999",
    newPrice: "2000",
    company: "Adidas",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2500",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71QyxJ8v-NL._SX695_.jpg",
    title: "Saucony Women's Evolution",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2500",
    company: "Merrell",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "girls",
    color: "black",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Nike",
    color: "blue",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "Vans",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "girls",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "girls",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "girls",
    color: "red",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "2000",
    company: "girls",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "girls",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "1000",
    company: "girls",
    color: "white",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "girls",
    color: "black",
    category: "heels",
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "₹1,40,00",
    newPrice: "500",
    company: "girls",
    color: "black",
    category: "flats",
  },
  {
    img : "https://m.media-amazon.com/images/I/61QF80zLUsL._SY695_.jpg",
    title: "Adidas Mens Fluidflow",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(2222 reviews)",
    prevPrice: "₹22,222",
    newPrice: "2500",
    company: "Adidas",
    color: "white",
    category: "Sneakers",
  }
];

export default data;